# Generated by Django 3.2.8 on 2021-10-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
